SinWeight: 2
CosWeight: 5
VelocityWeight: 0.0
dt: 0.02
uReg: 0
xReg: 0
trajectory_node_weight: 1e-5
trajectory_terminal_weight: 1e5
running_model_goal_weight: 1e8
terminal_model_goal_weight: 1e5
tau_ub: 0.05
tau_lb: -0.05
T_ROUTE: 300
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 2
zero_the_initial_position: true
goto_base_position: true
use_callback_verbose: true
control_loop_iterations: -1