SinWeight: 2
CosWeight: 1.5
VelocityWeight: 0.01
dt: 0.02
uReg: 1e-6
xReg: 1e-6
trajectory_node_weight: 9e-4
trajectory_terminal_weight: 1e4
running_model_goal_weight: 5e-1
terminal_model_goal_weight: 1e5
tau_ub: 0.06
tau_lb: -0.06
T_ROUTE: 300
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 4
zero_the_initial_position: false
goto_base_position: false
use_callback_verbose: true
control_loop_iterations: -1