SinWeight: 2
CosWeight: 1.5
VelocityWeight: 0.08
dt: 0.025
uReg: 1e-6
xReg: 1e-6
trajectory_node_weight: 2e-3
trajectory_terminal_weight: 1e7
running_model_goal_weight: 1e6
terminal_model_goal_weight: 1e6
tau_ub: 0.06
tau_lb: -0.06
T_ROUTE: 300
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 4
zero_the_initial_position: true
goto_base_position: true
use_callback_verbose: true
control_loop_iterations: -1