SinWeight: 2.0
CosWeight: 2.0
VelocityWeight: 0.05
dt: 0.01
uReg: 1e-6
xReg: 1e-6
running_model_goal_weight: 1e-3
terminal_model_goal_weight: 1e4
tau_ub: 0.05
tau_lb: -0.05
T_ROUTE: 300
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 1
zero_the_initial_position: true
goto_base_position: true
use_callback_verbose: false
control_loop_iterations: 1