SinWeight: 2
CosWeight: 2
VelocityWeight: 0.1
dt: 0.02
uReg: 1e-4
xReg: 1e-8
trajectory_node_weight: 1e-3
trajectory_terminal_weight: 1e4
running_model_goal_weight: 1e-1
terminal_model_goal_weight: 1e4
tau_ub: 0.05
tau_lb: -0.05
T_ROUTE: 300
T_MPC: 10
initial_solver_iterations: 1000
solver_iterations: 100
zero_the_initial_position: false
goto_base_position: true
use_callback_verbose: true
control_loop_iterations: -1
