SinWeight: 2
CosWeight: 2
VelocityWeight: 0.3
dt: 0.05
uReg: 1e-4
xReg: 1e-8
trajectory_node_weight: 1e-5
trajectory_terminal_weight: 1e5
running_model_goal_weight: 1e-5
terminal_model_goal_weight: 5e5
tau_ub: 0.06
tau_lb: -0.06
T_ROUTE: 300
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 8
zero_the_initial_position: false
goto_base_position: true
use_callback_verbose: true
control_loop_iterations: -1
