SinWeight: 2
CosWeight: 2
VelocityWeight: 0.01
dt: 0.01
uReg: 1e-6
xReg: 1e-6
running_model_goal_weight: 1e4
terminal_model_goal_weight: 1e4
tau_ub: 0.05
tau_lb: -0.05
T_OCP: 150
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 2
zero_the_initial_position: true
goto_base_position: true
add_callback_verbose: true
control_loop_iterations: -1