SinWeight: 1
CosWeight: 1
VelocityWeight: 0.3
dt: 0.03
uReg: 1e-6
xReg: 1e-6
trajectory_node_weight: 2e-5
trajectory_terminal_weight: 1e5
running_model_goal_weight: 2e-5
terminal_model_goal_weight: 1e5
tau_ub: 0.1
tau_lb: -0.1
T_ROUTE: 300
T_MPC: 100
initial_solver_iterations: 8000
solver_iterations: 6
zero_the_initial_position: true
goto_base_position: true
use_callback_verbose: true
control_loop_iterations: -1